from repositories.sql_repository.sql_repo_items import ItemSQLRepository
from repositories.sql_repository.sql_repo_transactions import TransactionSQLRepository
from repositories.sql_repository.sql_repo_inventory import InventorySQLRepository

current_item_repo = ItemSQLRepository
current_transaction_repo = TransactionSQLRepository
current_inventory_repo = InventorySQLRepository
