from repositories.sql_repository.items import ItemSQLRepository
from repositories.sql_repository.transactions import TransactionSQLRepository
from repositories.sql_repository.inventory import InventorySQLRepository

current_item_repo = ItemSQLRepository
current_transaction_repo = TransactionSQLRepository
current_inventory_repo = InventorySQLRepository