from repositories.sql_repository.items import ItemSQLRepository
from repositories.sql_repository.transactions import TransactionSQLRepository

current_item_repo = ItemSQLRepository
current_transaction_repo = TransactionSQLRepository
